spring:
  shardingsphere:
    datasource:
      names: master-0,master-1,master-0-slave-0,master-1-slave-0
      master-0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.1.15:3306/study0?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: liberty123

      master-1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.1.15:3306/study1?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: liberty123

      master-0-slave-0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.1.15:3308/study0?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: liberty123

      master-1-slave-0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.1.15:3308/study1?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: liberty123

    sharding:
      tables:
        user:
          actual-data-nodes: ds-$->{0..1}.user_$->{0..2}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: user_$->{id % 3}
          database-strategy:
            inline:
              sharding-column: id
              algorithm-expression: ds-$->{id % 2}


        balance:
          actual-data-nodes: ds-$->{0..1}.balance_$->{0..2}
          table-strategy:
            inline:
              sharding-column: user_id
              algorithm-expression: balance_$->{user_id % 3}
          database-strategy:
            inline:
              sharding-column: user_id
              algorithm-expression: ds-$->{user_id % 2}

        product:
          actual-data-nodes: ds-$->{0..1}.product_$->{0..2}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: product_$->{id % 3}
          database-strategy:
            inline:
              sharding-column: id
              algorithm-expression: ds-$->{id % 2}

      binding-tables: user,balance,product
      default-data-source-name: ds-0
      default-database-strategy:
        inline:
          sharding-column: id
          algorithm-expression: ds-$->{id % 2}

      master-slave-rules:
        ds-0:
          master-data-source-name: master-0
          slave-data-source-names: master-0-slave-0
        ds-1:
          master-data-source-name: master-1
          slave-data-source-names: master-1-slave-0
    props:
      sql:
        show: false